name: Actualizar idiomas soportados
on:
  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │ ┌───────────── hour (0 - 23)
    #        │ │  ┌───────────── day of the month (1 - 31)
    #        │ │  │   ┌───────────── month (1 - 12 or JAN-DEC)
    #        │ │  │   │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │ │  │   │ │
    #        │ │  │   │ │
    #        │ │  │   │ │
    #        * *  *   * *
    - cron: "0 0 */30 * *"

permissions:
  contents: read

jobs:
  updateLanguages:
    if: github.repository == 'alvar3zjos3/dev-readme-stats'
    name: Actualizar idiomas soportados
    runs-on: ubuntu-latest

    permissions:
      actions: read
      checks: read
      contents: write
      deployments: read
      issues: read
      discussions: read
      packages: read
      pages: read
      pull-requests: write
      repository-projects: read
      security-events: read
      statuses: read

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci
        env:
          CI: true

      - name: Run update-languages-json.js script
        run: npm run generate-langs-json

      - name: Create Pull Request if upstream language file is changed
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          commit-message: "refactor: update languages JSON"
          branch: "update_langs/patch"
          delete-branch: true
          title: Update languages JSON
          body:
            "The
            [update-langs](https://github.com/alvar3zjos3/dev-readme-stats/actions/workflows/update-langs.yaml)
            action found new/updated languages in the [upstream languages JSON
            file](https://raw.githubusercontent.com/github/linguist/master/lib/linguist/languages.yml)."
          labels: "ci, lang-card"
